# Generated by Django 5.1.4 on 2025-02-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengertraveldetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passengertraveldetails',
            name='mobile_number',
        ),
        migrations.CreateModel(
            name='PayeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('passenger_travel_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obrs_app.passengertraveldetails')),
            ],
        ),
    ]
