# Generated by Django 5.1.4 on 2025-02-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0003_remove_passengertraveldetails_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengertraveldetails',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='payeedetails',
            name='passenger_travel_details',
        ),
        migrations.AddField(
            model_name='passengertraveldetails',
            name='payee_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obrs_app.payeedetails'),
        ),
    ]
