# Generated by Django 5.1.4 on 2025-02-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0004_remove_passengertraveldetails_traveler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obrs_app.bus'),
        ),
    ]
