# Generated by Django 5.1.4 on 2025-02-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0005_employee_assigned_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='assigned_bus',
        ),
        migrations.CreateModel(
            name='EmployeeBusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrs_app.bus')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrs_app.employee')),
            ],
        ),
    ]
