# Generated by Django 5.1.4 on 2025-02-08 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0006_remove_employee_assigned_bus_employeebusassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obrs_app.schedule'),
        ),
    ]
