# Generated by Django 5.1.4 on 2025-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0008_journeydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydate',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='journeydate',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
