# Generated by Django 5.1.4 on 2025-02-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0009_alter_journeydate_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydate',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obrs_app.employee'),
            preserve_default=False,
        ),
    ]
