# Generated by Django 5.1.4 on 2025-02-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0010_journeydate_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obrs_app.booking'),
        ),
    ]
