# Generated by Django 5.1.4 on 2025-02-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0011_cancellation_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='booking_id_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
