# Generated by Django 5.1.4 on 2025-02-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0012_cancellation_booking_id_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='seat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
