# Generated by Django 5.1.4 on 2025-02-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0013_cancellation_schedule_cancellation_seat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellation',
            name='seat_number',
        ),
    ]
