# Generated by Django 5.1.4 on 2025-02-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0014_remove_cancellation_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeedetails',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obrs_app.booking'),
        ),
    ]
