# Generated by Django 5.1.4 on 2025-02-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0015_payeedetails_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengertraveldetails',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obrs_app.bus'),
        ),
    ]
