# Generated by Django 5.1.4 on 2025-02-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0016_passengertraveldetails_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebusassignment',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obrs_app.schedule'),
            preserve_default=False,
        ),
    ]
