# Generated by Django 5.1.4 on 2025-02-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0017_employeebusassignment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebusassignment',
            name='schedule',
        ),
    ]
