# Generated by Django 5.1.4 on 2025-03-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0022_snack'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrs_app.passenger')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrs_app.snack')),
            ],
        ),
    ]
