# Generated by Django 5.1.4 on 2025-03-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0024_alter_snackorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snacks/'),
        ),
    ]
