# Generated by Django 5.1.4 on 2025-03-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0025_snack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='snackorder',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obrs_app.booking'),
        ),
    ]
