# Generated by Django 5.1.4 on 2025-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0027_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackorder',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
