# Generated by Django 5.1.4 on 2025-04-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0029_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_type',
        ),
        migrations.AddField(
            model_name='bus',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
    ]
