# Generated by Django 5.1.4 on 2025-04-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0030_remove_bus_bus_type_bus_base_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
