# Generated by Django 5.1.4 on 2025-04-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0031_bus_bus_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
    ]
