# Generated by Django 5.1.4 on 2025-04-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0032_remove_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='travel_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
