# Generated by Django 5.1.4 on 2025-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrs_app', '0033_bus_travel_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
